// ── Project → landmark registry (single source of truth) ────────────────
// Each project LIVES INSIDE an iconic landmark from Japan or Taiwan. The
// entry places the landmark in the city AND drives its HUD card + minimap.
// `pos` is the [x, z] anchor in world units. `landmark` picks the builder in
// world/factory (see LANDMARK_BUILDERS in World.js). `venue` is the display
// name of the place. `enterR` = proximity radius that pops the tooltip.
// `href:null` => private (no CTA). Screenshot paths are PLAIN RELATIVE so
// they resolve on GitHub Pages (/Portfolio/) and Netlify (root) identically.

export const SHOTS = 'assets/screenshots/'

export const projects = [
  {
    id: 'oro-realstate',
    title: 'Oro RealState',
    category: 'Real Estate',
    status: 'LIVE',
    href: 'https://oro-real-state.vercel.app/',
    linkLabel: 'Open live app',
    stack: 'Next.js · Supabase · Resend',
    blurb: 'Rental operations dashboard: properties, leases, payments, receipts, reminders and maintenance.',
    accent: '#e0a93c',
    glyph: 'OR',
    screenshot: SHOTS + 'oro-realstate-panel.png',
    thumbs: [SHOTS + 'oro-realstate-properties.png', SHOTS + 'oro-realstate-payments.png', SHOTS + 'oro-realstate-reminders.png'],
    landmark: 'tokyoTower', venue: 'Tokyo Tower', district: 'japan',
    pos: [0, -27], rotY: 0, enterR: 9.5,
  },
  {
    id: 'ai-wealth-lab',
    title: 'AI Wealth Lab',
    category: 'AI / Finance',
    status: 'REPO',
    href: 'https://github.com/Orosergio/RegimeAwareGBWM',
    linkLabel: 'View repository',
    stack: 'Python · RL · G-Learner / PPO',
    blurb: 'Regime-aware goal-based wealth simulator: RL agents, HMM regime detection, no-lookahead backtests.',
    accent: '#3a6fb0',
    glyph: 'WL',
    screenshot: null,
    thumbs: [],
    landmark: 'taipei101', venue: 'Taipei 101', district: 'taiwan',
    pos: [0, 27], rotY: 0, enterR: 9.5,
  },
  {
    id: 'openclaw',
    title: 'OpenClaw Mission',
    category: 'AI Infra',
    status: 'LIVE',
    href: 'visual-campaign-board-founder-copilot-for-telegram-2026-04-05-premium.html',
    linkLabel: 'Open a live board',
    stack: 'Python · Next · Hetzner VPS',
    blurb: 'Telegram-native AI workflow on a hardened Linux VPS that renders structured briefs into HTML boards.',
    accent: '#5b6cc0',
    glyph: 'OC',
    screenshot: null,
    thumbs: [],
    landmark: 'skytree', venue: 'Tokyo Skytree', district: 'japan',
    pos: [17, -16.5], rotY: 0, enterR: 8,
  },
  {
    id: 'pattern-journal',
    title: 'Pattern Journal',
    category: 'AI Product',
    status: 'LIVE',
    href: 'https://pattern-journal.vercel.app',
    linkLabel: 'Open live app',
    stack: 'Next.js · TS · Gemini 2.5',
    blurb: 'AI journaling that detects emotional patterns, charts sentiment, and writes weekly insight reports.',
    accent: '#4fa3c7',
    glyph: 'PJ',
    screenshot: SHOTS + 'pattern-journal-dashboard.png',
    thumbs: [SHOTS + 'pattern-journal-write.png', SHOTS + 'pattern-journal-history.png', SHOTS + 'pattern-journal-insights.png'],
    landmark: 'fushimi', venue: 'Fushimi Inari Path', district: 'japan',
    pos: [-27, -9], rotY: 0, enterR: 10.5,
  },
  {
    id: 'kiniela',
    title: 'Kiniela Mundial',
    category: 'Full-stack',
    status: 'REPO',
    href: 'https://github.com/Orosergio/KinielaFulbrings',
    linkLabel: 'View repository',
    stack: 'React · Netlify · Neon Postgres',
    blurb: 'Private World Cup pool: auth, groups, predictions, live score sync, server-side rules and DB triggers.',
    accent: '#3fa08a',
    glyph: 'KM',
    screenshot: SHOTS + 'kiniela-home.png',
    thumbs: [SHOTS + 'kiniela-predictions.png', SHOTS + 'kiniela-group.png'],
    landmark: 'stadium', venue: 'Taipei Dome', district: 'taiwan',
    pos: [13.5, 13.5], rotY: 0, enterR: 10,
  },
  {
    id: 'finger-mouse',
    title: 'Finger Mouse',
    category: 'Embedded',
    status: 'PRIVATE',
    href: null,
    linkLabel: 'Private case study',
    stack: 'Zephyr · C · nRF52840',
    blurb: 'BLE HID firmware for a wearable mouse: optical tracking, force + capacitive sensors, haptics, MCUboot DFU.',
    accent: '#6b7a8f',
    glyph: 'FM',
    screenshot: null,
    thumbs: [],
    landmark: 'akihabara', venue: 'Akihabara', district: 'japan',
    pos: [13, -7], rotY: 0, enterR: 7.5,
  },
  {
    id: 'milingua',
    title: 'Milingua',
    category: 'Mobile',
    status: 'PRIVATE',
    href: null,
    linkLabel: 'Private build',
    stack: 'Flutter · Supabase · PostHog',
    blurb: 'Mobile-first real-time translation for frontline service: transcripts, glossary quality, pilot analytics.',
    accent: '#e8704a',
    glyph: 'ML',
    screenshot: null,
    thumbs: [],
    landmark: 'nightMarket', venue: 'Raohe Night Market', district: 'taiwan',
    pos: [0, 8.4], rotY: 0, enterR: 7,
  },
  {
    id: 'inmob',
    title: 'Inmob Recovery',
    category: 'Recovery',
    status: 'ARCHIVE',
    href: null,
    linkLabel: 'Archived project',
    stack: 'Node · Express · EJS · MariaDB',
    blurb: 'Recovered university rental platform: auth, sessions, listings, reservations, uploads, DB setup scripts.',
    accent: '#9a6b8f',
    glyph: 'IR',
    screenshot: null,
    thumbs: [],
    landmark: 'longshan', venue: 'Longshan Temple', district: 'taiwan',
    pos: [-14, 13.5], rotY: 0, enterR: 8.5,
  },
]
